### ISSUE TITLE
Things you tried that worked very well!

### ISSUE THREAD

**Issue by developer0hye** [yjh0410/CenterNet-plus#5]
Hi, yjh!

I am curious about what methods make your CenterNet powerful!

Is there experiment results related to below contents?

SPP vs Dilated Encoder

Concat vs Summation for Neck

with Iou aware branch vs without Iou aware branch

**Comment by yjh0410** [comment]
Hi!

To be honest, I didn’t expect my model to work so well.

I think the DilatedEncoder really improve my CenterNet since it can expand the receptive field to improve the AP of large objects.

When I replaced the deconv with upsample + 1x1 conv, my CenterNet has hardly improved.(about 25AP with ResNet-18 backbone). Equipped with the DilatedEncoder, my model got 28.4 AP. 

Then, I added IoU loss to my loss function and got 29.4 AP. With Iou-aware loss, the AP rose to 29.9.

I will do more ablation experiments to study each detail of my model.

**Comment by developer0hye** [comment]
@yjh0410 
Thanks for your reply! Can you expect if we use good backbone and neck architecture, we can reach yolov4's performance with acceptable speed?

**Comment by yjh0410** [comment]
I think it is possible. My model is so simple that we can continue to improve it with many tricks or other excellent networks.

My decoder just consists of several simple conv layers, and we can add more layers (except P2 as it is too big).

**Comment by developer0hye** [comment]
Great!

Detection on p3 can be a good choice for realtime detector.

When I test detection on p3, there are no margin in comparison to detection on p2. 

The size of featuremap p2 is too big.

**Comment by yjh0410** [comment]
Yeah, I agree with you.

I plan to build a lightweight version of CenterNet-plus, and I will consider your advice that make it only detect on p3, not p2.
